### ISSUE TITLE
Include information about downtime(s)

### ISSUE THREAD

**Issue by wbobeirne** [findbl0k/bitcoinUptime#6]
Just stumbled across this site, very cool! The first thing I did was look into the code to see how the time was calculated, and how downtimes were accounted for. I was happy to see the detailed comments with links. It would be cool if the downtimes were displayed on the site for people to learn more.

**Comment by findbl0k** [comment]
Just merged this pull request. Downtime events are now displayed.

https://github.com/findbl0k/bitcoinUptime/pull/7#issue-253635904
